### ISSUE TITLE
[Roadmap] Frontend UI framework

### ISSUE THREAD

**Issue by RyanTheAllmighty** [ATLauncher/ATLauncher-NEXT#4]
Need to choose a frontend UI framework to be used.

Some examples are:

- [Bootstrap](http://getbootstrap.com)
- [Bulma](http://bulma.io)
- [Materialize](http://materializecss.com/)
- Custom framework using things like Flexbox. See comment below

**Comment by jamierocks** [comment]
Since this is a desktop app perhaps material design might be nice to use. I would go for materialise

**Comment by RyanTheAllmighty** [comment]
I think this will ultimately be a less important decision and based more around whatever UI design is mocked up.

**Comment by Ryahn** [comment]
From a designing standpoint, Bootstrap is the most widely used but from reading about them. Bulma and Materalize seem to fit the bill a little better for ATL.

**Comment by RyanTheAllmighty** [comment]
Another option is not using a UI framework and instead building our own simplified one.

I've discovered the joys of Flexbox and think it may be ideal in order to keep thing lightweight and minimal

**Comment by jamierocks** [comment]
It would probably be more work, but there would be more control over the design

**Comment by Ryahn** [comment]
I agree with @jamierocks. Flexbox might be the way to go

**Comment by Isigiel** [comment]
I do like Bulma a lot, think about releasing react bindings for it if you chose it.

**Comment by RyanTheAllmighty** [comment]
Styleguide approach is preferred for more control, but I don't see it happening unfortunately with the current resources, so using an existing framework may be the way to go.

**Comment by RyanTheAllmighty** [comment]
Will be using our own styleguide with a react implementation of the components available for ease of use
