### ISSUE TITLE
[Roadmap] Semver Versioning

### ISSUE THREAD

**Issue by RyanTheAllmighty** [ATLauncher/ATLauncher-NEXT#7]
The launcher itself will be using [Semver](http://semver.org/) for all it's versioning starting with 4.0.0 and incrementing as per Semver rules.

Ideally I'd like to move all pack versioning over to semver as the advantages it offers knowing that every version follows it means there is a lot of nice things we can do such as proper update blocking/allowing rules.

The problem is this will require that most packs update all their old and future versions to this new format since at the moment packs can use free range of version as long as it's alpha numeric.

This is simple enough to simply not allow the launcher to see packs that are non semver, it may cause some issue with pack devs.

This will need to be mentioned to pack developers to gain their thoughts.

I'll do some tagging here to some pack devs I know are active on Github: @reteo @GodNero @BBolt @leagris @Cherry

**Comment by leagris** [comment]
@RyanTheAllmighty This is good for libraries and software applications. But Mod-Packs are packaging mods from many different sources and lax if no proper versionning standard..
As most mods are backward incompatible, it means you would have to increment major version# for each mod incompatible version change in a Mod-Pack.
See: [Semantic Versioning 2.0.0](http://semver.org/#if-even-the-tiniest-backwards-incompatible-changes-to-the-public-api-require-a-major-version-bump-wont-i-end-up-at-version-4200-very-rapidly)
> This is a question of responsible development and foresight. Incompatible changes should not be introduced lightly to software that has a lot of dependent code. The cost that must be incurred to upgrade can be significant. Having to bump major versions to release incompatible changes means you’ll think through the impact of your changes, and evaluate the cost/benefit ratio involved.

**Comment by reteo** [comment]
Hmmm... this could be good for automation, and for consistency.  However, some people have numbering conventions based on specific goals.

I'll use my own modpack for an example: Survival Industry's numbering system will usually do a patchlevel bump for minor mod upgrades, a minor version bump for major upgrades (such as si.core overhauls or Reika upgrades), but the major version number will not be touched unless the Minecraft version itself is upgraded (Survival Industry 1 should always be using Minecraft 1.7.10, Survival Industry 2 should only come out when the required version of Minecraft is updated, perhaps 1.8.9?).  This way, the numbering tracks the foundations of the modpack itself, letting the players know whether major changes have been performed, and giving them an idea what those changes are.

**Comment by RyanTheAllmighty** [comment]
Yeah see my reasoning behind wanting to do this for pack versions is consistency.

At the moment I cannot do jack shit with the versions packs give me since everyone uses something different. That makes doing things like proper version locking to prevent updates to breaking versions.

I mean I can understand why not to do it, but I figured I'd open the conversation about it, it's not something we'll do if people aren't happy for it, it's just definitely a much easier solution for consistency as a base of several additions we'd like to make, but we can work around them.

**Comment by reteo** [comment]
Maybe I should start by understanding what you're referring to; what exactly do you mean by "version locking?"  How would you determine if a pack meets or violates the standards?  How would it be detected?

**Comment by RyanTheAllmighty** [comment]
Well at the moment you have the ability to disable updating to a specific version of a pack. This at the moment is kind of limited in it's use since you can technically only use it on the first breaking update (say from MC 1.6.4 to 1.7.10) since if you use it on your second 1.7.10 version then it will deny the update to those who use the 1.7.10 version you first put out.

Ideal what I'd liked to have done is allow pack developers to specify 'locking' as it were to versions to simply provide a semver statement to say that updates can only be done from this version to anything matching this version.

I'd not thought about it too much, and while it can be done with more work from pack developers providing their own version regexes and statements, it would be much easier to be working off of semver but I can see it's probably best to not happen.

**Comment by leagris** [comment]
Here is what we do for Beyond Reality:
* X ⇒ Major version increment for each MC version or world breaking change
* Y ⇒ Minor version increment for major mod updates, features changes
* Z ⇒ Patch version increment for mod maintenance upgrades (mods bugfixes)
* We also add revision identifiers [a-z] for minor config changes and backward compatibles hotfixes

So, adapting this to Semantic versionning is a minor tweak with changing syntax for our revision identifiers.
Though, stricto sensu, this does not exactly fit Semver rules.

Semver should be put as a recommendation rather than a requirement.
Could be ATLauncher guidelines for how to implement these versionning rules on a Mod-Pack.

**Comment by reteo** [comment]
I wouldn't completely write it off.  While semantic versioning would not be the best solution, some level of standardization could be useful.

One possibility: The modpack author can be given an XML tag for the modpack to determine if they want the major version number tracking the update to the underlying Minecraft version.  Then, they could be given mod attributes that can mark mods as either "major key" (upgrading the mod will upgrade the pack's major version number) or "minor key" (ditto with minor version number), leaving the patchlevel to be defined by the modpack author themselves.

**Comment by Ryahn** [comment]
Resonant Rise could definitely benefit from having this. Managing 2-3 mod packs and versions each, would make this a lot easier. But I do agree with @leagris on the versioning.

**Comment by RyanTheAllmighty** [comment]
Alright so definitely a no go on the force use of semver, I'll have to spend some time looking into alternatives for what I'd like to achieve and more work into standardisation or at least recommendations.

**Comment by Ryahn** [comment]
Is it still possible to make it to where we could warn users about using an outdated version of packs? 

We tend to make a lot of fixes and users tend to still use old versions.

**Comment by RyanTheAllmighty** [comment]
If you've not already done so, I suggest popping an issue in https://github.com/ATLauncher/ATLauncher/issues

**Comment by RyanTheAllmighty** [comment]
This will be discussed in the implementation phase for packs, but as far as the launcher iteself goes, 4.0.0 will be initial version released and then following semver from that point on
