### ISSUE TITLE
[Roadmap] Branching structure

### ISSUE THREAD

**Issue by RyanTheAllmighty** [ATLauncher/ATLauncher-NEXT#9]
This details the way we want to branch out and organise the codes branches.

This is based on [Gitflow Workflow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow).

 - **master** will always contain the code for the latest release
 - **develop** will contain the latest development version for beta testing enrolled users
 - **features/*** will contain single issues being developed. Once developed they're merged into develop and tagged with a beta release version. They should be named 'features/22-some-brief-description'
 - **releases/*** will contain all the code from each feature branch that are going out in the next release and should all be merged into the branch. Once approved and tested it gets merged into master and tagged. They should be named 'releases/4-1-1-release'
 - **hotfixes/*** will contain hotfixes going to be merged directly into master then tagged. Hotfixes should only need to occur when there is a very critical bug in the current release that needs to be fixed ASAP. All hotfix branches should be branched off of master.

Feature branches are deleted once in a release branch. Any issues that come up after the features branch has been merged into a release branch should be resolved by creating a new feature branch off the release branch.

An example of a good name for a feature branch is say we have an issue (#44) which is about users not being able to download modpacks on Sunday. A good name for a feature branch would be `features/44-unable-to-download-modpacks-on-sunday` and go from there.

While the initial development goes on, a temporary 'initial-code' branch will be used them merged into develop when testing is ready.

**Comment by RyanTheAllmighty** [comment]
No opposition to this, so sticking with this

**Comment by jamierocks** [comment]
If I were you I would use the singular not the plural

**Comment by RyanTheAllmighty** [comment]
That works
